# Generated by Django 3.2.8 on 2021-10-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(default='SampleName', max_length=60)),
                ('website_link', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
