# Generated by Django 3.2.8 on 2021-11-02 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shredder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResortCompany',
            fields=[
                ('resort_company_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('resort_name', models.CharField(choices=[('Ikon', 'Ikon'), ('Epic', 'Epic'), ('Other', 'Other')], default='Other', max_length=12)),
                ('website_link', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.RenameField(
            model_name='mountain',
            old_name='id',
            new_name='mountain_id',
        ),
        migrations.AlterField(
            model_name='mountain',
            name='website_link',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='mountain',
            name='resort_company',
            field=models.ForeignKey(default='Other', on_delete=django.db.models.deletion.CASCADE, to='shredder.resortcompany'),
        ),
    ]
