# Generated by Django 3.2.9 on 2021-11-20 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=10)),
                ('longitude', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('state', models.CharField(choices=[('Colorado', 'Colorado'), ('Utah', 'Utah'), ('Idaho', 'Idaho'), ('California', 'California'), ('Washington', 'Washington'), ('Minnesota', 'Minnesota'), ('New York', 'Newyork'), ('Vermont', 'Vermont'), ('New Hampshire', 'Newhampshire'), ('Pennsylvania', 'Pennsylvania'), ('Maine', 'Maine'), ('New Mexico', 'Newmexico'), ('Oregon', 'Oregon'), ('West Virginia', 'Westvirginia'), ('Wyoming', 'Wyoming'), ('Canada', 'Canada')], default='Colorado', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ResortCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort_name', models.CharField(choices=[('Ikon', 'Ikon'), ('Epic', 'Epic'), ('Other', 'Other')], default='Other', max_length=12)),
                ('website_link', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SampleName', max_length=60)),
                ('website_link', models.CharField(blank=True, max_length=120)),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mountains.location')),
                ('resort_company', models.ForeignKey(default='Other', on_delete=django.db.models.deletion.CASCADE, to='mountains.resortcompany')),
            ],
        ),
    ]
