# Generated by Django 3.2.8 on 2021-11-02 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResortCompany',
            fields=[
                ('resort_company_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('resort_name', models.CharField(choices=[('Ikon', 'Ikon'), ('Epic', 'Epic'), ('Other', 'Other')], default='Other', max_length=12)),
                ('website_link', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('mountain_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(default='SampleName', max_length=60)),
                ('website_link', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('resort_company', models.ForeignKey(default='Other', on_delete=django.db.models.deletion.CASCADE, to='mountains.resortcompany')),
            ],
        ),
    ]
