# Generated by Django 3.2.8 on 2021-11-12 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0001_initMigration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('latitude', models.CharField(blank=True, max_length=10)),
                ('longitude', models.CharField(blank=True, max_length=10)),
                ('state', models.CharField(choices=[('Colorado', 'Colorado'), ('Utah', 'Utah'), ('Idaho', 'Idaho'), ('California', 'California'), ('Washington', 'Washington'), ('Minnesota', 'Minnesota'), ('New York', 'Newyork'), ('Vermont', 'Vermont'), ('New Hampshire', 'Newhampshire'), ('Pennsylvania', 'Pennsylvania'), ('Maine', 'Maine'), ('New Mexico', 'Newmexico'), ('Oregon', 'Oregon'), ('West Virginia', 'Westvirginia'), ('Wyoming', 'Wyoming'), ('Canada', 'Canada')], default='Colorado', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='mountain',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mountains.location'),
        ),
    ]
