# Generated by Django 3.2.8 on 2022-10-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0003_add_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='state_code',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
